### ISSUE TITLE
HW02 graded

### ISSUE THREAD

**Issue by mtaylor-semo** [gabd-students/kleinberg_donovan#3]
Does not appear you completed parts 3-6.

**Comment by Donovan-Klein** [comment]
I did all parts yet it appears my git commit practice was not up to snuff with that assignment and I was making a mistake somewhere along the line while doing the commit and push process. If you want them for partial credit I can do that, if not it will be a learning experience for me to properly check my commits.

**Comment by mtaylor-semo** [comment]
Commit and push them.
